### ISSUE TITLE
Notecrumbs profile pages

### ISSUE THREAD

**Issue by alltheseas** [damus-io/notecrumbs#10] opened 2024-02-12 21:02 UTC
_currently_

![Screenshot 2024-02-12 at 3 01 41 PM](https://github.com/damus-io/notecrumbs/assets/64376233/82d26213-f957-41c0-a9c5-22e4223be55d)

_examples from other nostr apps_

njump.me

![Screenshot 2024-02-12 at 3 02 47 PM](https://github.com/damus-io/notecrumbs/assets/64376233/1f798c88-e5bf-4711-87b3-7a4d4762d889)

**Comment by jb55** [comment] 2024-12-27 18:23
Duplicate of #1

**Closed by jb55** 2024-12-27 18:23 UTC
Labels: enhancement
